// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZeroTrustSaaS.Infrastructure.Persistence;

#nullable disable

namespace ZeroTrustSaaS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630215748_RemovePlanAddMfaRecoveryCodes")]
    partial class RemovePlanAddMfaRecoveryCodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrustedDeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_logs_occurred_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audit_logs_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Authorization.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Authorization.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Authorization.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Authorization.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RoleId", "TenantId")
                        .HasDatabaseName("ix_user_roles_user_role_tenant");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Devices.TrustedDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TrustedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trusted_devices_user_id");

                    b.ToTable("trusted_devices", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Identity.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_attempts_user_id");

                    b.ToTable("login_attempts", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByRefreshTokenId")
                        .HasColumnType("uuid");

                    b.Property<int>("RevocationReason")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFailedLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MfaMethod")
                        .HasColumnType("integer");

                    b.Property<string>("MfaRecoveryCodeHashes")
                        .HasColumnType("text")
                        .HasColumnName("mfa_recovery_code_hashes");

                    b.Property<DateTime>("PasswordChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Platform.PlatformConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InitializedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsInitialized")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("platform_configuration", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Tenants.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_memberships_tenant_user");

                    b.ToTable("tenant_memberships", (string)null);
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Audit.AuditLog", b =>
                {
                    b.OwnsOne("ZeroTrustSaaS.Domain.Security.IpAddress", "IpAddress", b1 =>
                        {
                            b1.Property<Guid>("AuditLogId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("character varying(45)")
                                .HasColumnName("ip_address");

                            b1.HasKey("AuditLogId");

                            b1.ToTable("audit_logs");

                            b1.WithOwner()
                                .HasForeignKey("AuditLogId");
                        });

                    b.Navigation("IpAddress");
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Authorization.Permission", b =>
                {
                    b.OwnsOne("ZeroTrustSaaS.Domain.Authorization.PermissionCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("PermissionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("code");

                            b1.HasKey("PermissionId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_permissions_code");

                            b1.ToTable("permissions");

                            b1.WithOwner()
                                .HasForeignKey("PermissionId");
                        });

                    b.Navigation("Code")
                        .IsRequired();
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Authorization.Role", b =>
                {
                    b.OwnsOne("ZeroTrustSaaS.Domain.Authorization.RoleName", "Name", b1 =>
                        {
                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");

                            b1.HasKey("RoleId");

                            b1.ToTable("roles");

                            b1.WithOwner()
                                .HasForeignKey("RoleId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Authorization.RolePermission", b =>
                {
                    b.HasOne("ZeroTrustSaaS.Domain.Authorization.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ZeroTrustSaaS.Domain.Authorization.PermissionCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("RolePermissionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("code");

                            b1.HasKey("RolePermissionId");

                            b1.ToTable("role_permissions");

                            b1.WithOwner()
                                .HasForeignKey("RolePermissionId");
                        });

                    b.Navigation("Code")
                        .IsRequired();
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Devices.TrustedDevice", b =>
                {
                    b.OwnsOne("ZeroTrustSaaS.Domain.Devices.DeviceName", "Name", b1 =>
                        {
                            b1.Property<Guid>("TrustedDeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("TrustedDeviceId");

                            b1.ToTable("trusted_devices");

                            b1.WithOwner()
                                .HasForeignKey("TrustedDeviceId");
                        });

                    b.OwnsOne("ZeroTrustSaaS.Domain.Devices.ClientInfo", "ClientInfo", b1 =>
                        {
                            b1.Property<Guid>("TrustedDeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Browser")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("browser");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<string>("OperatingSystem")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("operating_system");

                            b1.HasKey("TrustedDeviceId");

                            b1.ToTable("trusted_devices");

                            b1.WithOwner()
                                .HasForeignKey("TrustedDeviceId");

                            b1.OwnsOne("ZeroTrustSaaS.Domain.Devices.DeviceFingerprint", "DeviceFingerprint", b2 =>
                                {
                                    b2.Property<Guid>("ClientInfoTrustedDeviceId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("device_fingerprint");

                                    b2.HasKey("ClientInfoTrustedDeviceId");

                                    b2.ToTable("trusted_devices");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientInfoTrustedDeviceId");
                                });

                            b1.OwnsOne("ZeroTrustSaaS.Domain.Security.IpAddress", "IpAddress", b2 =>
                                {
                                    b2.Property<Guid>("ClientInfoTrustedDeviceId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(45)
                                        .HasColumnType("character varying(45)")
                                        .HasColumnName("ip_address");

                                    b2.HasKey("ClientInfoTrustedDeviceId");

                                    b2.ToTable("trusted_devices");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientInfoTrustedDeviceId");
                                });

                            b1.Navigation("DeviceFingerprint")
                                .IsRequired();

                            b1.Navigation("IpAddress")
                                .IsRequired();
                        });

                    b.Navigation("ClientInfo")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Identity.LoginAttempt", b =>
                {
                    b.HasOne("ZeroTrustSaaS.Domain.Identity.User", null)
                        .WithMany("LoginAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ZeroTrustSaaS.Domain.Devices.ClientInfo", "ClientInfo", b1 =>
                        {
                            b1.Property<Guid>("LoginAttemptId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Browser")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("browser");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<string>("OperatingSystem")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("operating_system");

                            b1.HasKey("LoginAttemptId");

                            b1.ToTable("login_attempts");

                            b1.WithOwner()
                                .HasForeignKey("LoginAttemptId");

                            b1.OwnsOne("ZeroTrustSaaS.Domain.Devices.DeviceFingerprint", "DeviceFingerprint", b2 =>
                                {
                                    b2.Property<Guid>("ClientInfoLoginAttemptId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("device_fingerprint");

                                    b2.HasKey("ClientInfoLoginAttemptId");

                                    b2.ToTable("login_attempts");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientInfoLoginAttemptId");
                                });

                            b1.OwnsOne("ZeroTrustSaaS.Domain.Security.IpAddress", "IpAddress", b2 =>
                                {
                                    b2.Property<Guid>("ClientInfoLoginAttemptId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(45)
                                        .HasColumnType("character varying(45)")
                                        .HasColumnName("ip_address");

                                    b2.HasKey("ClientInfoLoginAttemptId");

                                    b2.ToTable("login_attempts");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientInfoLoginAttemptId");
                                });

                            b1.Navigation("DeviceFingerprint")
                                .IsRequired();

                            b1.Navigation("IpAddress")
                                .IsRequired();
                        });

                    b.Navigation("ClientInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("ZeroTrustSaaS.Domain.Identity.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ZeroTrustSaaS.Domain.Devices.ClientInfo", "IssuedClient", b1 =>
                        {
                            b1.Property<Guid>("RefreshTokenId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Browser")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("browser");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<string>("OperatingSystem")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("operating_system");

                            b1.HasKey("RefreshTokenId");

                            b1.ToTable("refresh_tokens");

                            b1.WithOwner()
                                .HasForeignKey("RefreshTokenId");

                            b1.OwnsOne("ZeroTrustSaaS.Domain.Devices.DeviceFingerprint", "DeviceFingerprint", b2 =>
                                {
                                    b2.Property<Guid>("ClientInfoRefreshTokenId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("device_fingerprint");

                                    b2.HasKey("ClientInfoRefreshTokenId");

                                    b2.ToTable("refresh_tokens");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientInfoRefreshTokenId");
                                });

                            b1.OwnsOne("ZeroTrustSaaS.Domain.Security.IpAddress", "IpAddress", b2 =>
                                {
                                    b2.Property<Guid>("ClientInfoRefreshTokenId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(45)
                                        .HasColumnType("character varying(45)")
                                        .HasColumnName("issued_ip");

                                    b2.HasKey("ClientInfoRefreshTokenId");

                                    b2.ToTable("refresh_tokens");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientInfoRefreshTokenId");
                                });

                            b1.Navigation("DeviceFingerprint")
                                .IsRequired();

                            b1.Navigation("IpAddress")
                                .IsRequired();
                        });

                    b.OwnsOne("ZeroTrustSaaS.Domain.Security.IpAddress", "RevokedByIp", b1 =>
                        {
                            b1.Property<Guid>("RefreshTokenId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("character varying(45)")
                                .HasColumnName("revoked_by_ip");

                            b1.HasKey("RefreshTokenId");

                            b1.ToTable("refresh_tokens");

                            b1.WithOwner()
                                .HasForeignKey("RefreshTokenId");
                        });

                    b.OwnsOne("ZeroTrustSaaS.Domain.Security.RefreshTokenHash", "TokenHash", b1 =>
                        {
                            b1.Property<Guid>("RefreshTokenId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("token_hash");

                            b1.HasKey("RefreshTokenId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_refresh_tokens_token_hash");

                            b1.ToTable("refresh_tokens");

                            b1.WithOwner()
                                .HasForeignKey("RefreshTokenId");
                        });

                    b.Navigation("IssuedClient")
                        .IsRequired();

                    b.Navigation("RevokedByIp");

                    b.Navigation("TokenHash")
                        .IsRequired();
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Identity.User", b =>
                {
                    b.OwnsOne("ZeroTrustSaaS.Domain.Identity.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_users_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ZeroTrustSaaS.Domain.Identity.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ZeroTrustSaaS.Domain.Security.MfaSecret", "MfaSecret", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("mfa_secret");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ZeroTrustSaaS.Domain.Security.SecurityStamp", "SecurityStamp", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("security_stamp");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("MfaSecret");

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("SecurityStamp")
                        .IsRequired();
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Tenants.Tenant", b =>
                {
                    b.OwnsOne("ZeroTrustSaaS.Domain.Tenants.TenantName", "Name", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("ZeroTrustSaaS.Domain.Tenants.TenantSlug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("slug");

                            b1.HasKey("TenantId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_tenants_slug");

                            b1.ToTable("tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Tenants.TenantMembership", b =>
                {
                    b.HasOne("ZeroTrustSaaS.Domain.Tenants.Tenant", null)
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Authorization.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Identity.User", b =>
                {
                    b.Navigation("LoginAttempts");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("ZeroTrustSaaS.Domain.Tenants.Tenant", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
